export const metadata = {
  title: "Shop Layout",
  description: "Shop - Generated by create next app",
};

import TitlePage from "@/components/pagesComponets/TitlePage";

const Shop = () => {
  return (
    <>
      <TitlePage title="Shop" />
    </>
  );
};
export default Shop;
